CREATE TABLE IF NOT EXISTS Shop(Id INTEGER,Name TEXT,AreaId INTEGER,AreaName TEXT,Status TEXT);
CREATE TABLE IF NOT EXISTS Product(Id INTEGER,Name TEXT,Description TEXT,Price TEXT,Path TEXT);
CREATE TABLE IF NOT EXISTS Orders(Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,ShopId INTEGER,UserId INTEGER,Total TEXT,OrderStatus INTEGER,OrderedDate TEXT,IsSync INTEGER);
CREATE TABLE IF NOT EXISTS OrderDetails(Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,OrderId INTEGER,ProductBrandId INTEGER,Price TEXT,Quantity INTEGER,IsSync INTEGER);